**Diabetes Prediction**

**IMPORTING THE REQUIRED LIBRARIES**

In [55]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [56]:
df = pd.read_csv(r'/content/diabetes.csv')

In [57]:
#TOP 5 ROWS
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [58]:
#BOTTOM 5 ROWS
df.tail()

     Pregnancies  Glucose  ...  Age  Outcome
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[5 rows x 9 columns]

In [59]:
#COLUMNS
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [60]:
#NUMBER OF ROWS AND COLUMNS
df.shape

(768, 9)

In [61]:
#statistical summary information
df.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [62]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [63]:
df.groupby('Outcome').mean()

         Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

**SPLITTING THE INPUT DATA**

In [64]:
X =df.drop(columns='Outcome' , axis=1)
y =df['Outcome']

In [65]:
X

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [66]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

**DATA STANDARDIZATION**

In [67]:
scaler = StandardScaler()

In [68]:
scaler.fit(X)

StandardScaler()

In [69]:
standard_data = scaler.transform(X)

In [70]:
standard_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [71]:
X = standard_data
y =df['Outcome']

In [72]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [73]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [74]:
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.2,stratify=y,random_state=2)

**TRAINIG THE MODEL**

In [75]:
classifier = svm.SVC(kernel='linear')

In [76]:
classifier.fit(X_train,y_train)

SVC(kernel='linear')

**MODEL EVALUATION**

In [77]:
#ACCURACY SCORE ON THE TRAINING DATA
X_train_pred = classifier.predict(X_train)
trainig_data_accuracy =accuracy_score(X_train_pred, y_train)

In [78]:
trainig_data_accuracy

0.7866449511400652

In [79]:
#ACCURACY SCORE ON THE TEST DATA
X_test_pred= classifier.predict(X_train)
test_data_accuracy =accuracy_score(X_test_pred, y_train)

In [80]:
test_data_accuracy

0.7866449511400652

**MAKING A PREDICTIVE SYSTEM**

In [84]:
input_data = (5,166,72,19,175,25.8,0.587,51)

columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
           'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']

# Convert into DataFrame
input_df = pd.DataFrame([input_data], columns=columns)

# Standardize
std_data = scaler.transform(input_df)

print(std_data)

# Prediction
prediction = classifier.predict(std_data)

print(prediction)

if prediction[0] == 0:
    print("THE PERSON IS NOT DIABETIC")
else:
    print("THE PERSON IS DIABETIC")

[[ 0.3429808   1.41167241  0.14964075 -0.09637905  0.82661621 -0.78595734
   0.34768723  1.51108316]]
[1]
THE PERSON IS DIABETIC